import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import UsersTable from '../components/Table'

const HomePage: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="p-10">
        <section className="explain">
          <div className="container text-left text-xs">
            Se solicita realizar una aplicación web que genere una API (Nest JS) que genere un
            servicio de usuarios haciendo uso de la siguiente fuente de datos:
            https://jsonplaceholder.typicode.com/users. Una vez realizados los end-points en
            Back-end, se deben consumir con React JS, donde las funcionalidades mínimas son:
          </div>
          <ul className='text-xs mt-2'>
            <li>● Lista de usuarios.</li>
            <li>● Lista de usuarios.</li>
            <li>● Filtro de usuarios por nombre (para vista de lista de usuarios).
              Consideraciones
            </li>
            <li>● La confirmación del desarrollo de la prueba, la debes enviar al buzón
                  pavel.franco@igloo-lab.com.
            </li>
            <li> ● Debes entregar la solución con el proyecto respectivo en github o similar, con
                  permisos para pavel.franco@igloo-lab.com y hugo.escobar@igloo-lab.com.
            </li>
            <li> ● Se espera que en el repositorio se encuentre un README donde se especifiquen
                  los pasos para correr el proyecto al descargarlo.
            </li>
            <li> ● Debes compartir la URL donde se puede consumir el proyecto desplegado.</li>
            <li> ● Tienes 3 días para desarrollar la prueba.</li>
          </ul>
        </section>
        <section className="users mt-5">
          <UsersTable />
        </section>
      </main>
    </div>
  )
}

export default HomePage
